version: "3.6"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  red-button_db:
    image: postgres:11-alpine
    container_name: red-button_db
    networks:
      - net
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=z2VT#&4nYid#
      - TZ=Australia/Perth
    volumes:
      - ./02_database_test.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data:/home/data
      - red-button_dbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  red-button_api:
    image: pgstevenson/red_button_api
    container_name: red-button_api
    restart: on-failure
    networks:
      - net
    ports:
      - 5000:5000
    depends_on:
      - red-button_db

networks:
  net:
    name: net

volumes:
  red-button_dbdata:
