version: "3.6"
services:
  red-button_db:
    image: postgres:11-alpine
    container_name: red-button_db
    networks:
      - net
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=z2VT#&4nYid#
      - TZ=Australia/Perth
    volumes:
      - ./01_database_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data:/home/data
      - dbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  red-button_api:
    image: pgstevenson/red_button_api
    container_name: red-button_api
    restart: on-failure
    networks:
      - net
    ports:
      - 5000:5000
    depends_on:
      - red-button_db

networks:
  net:
    name: net

volumes:
  red-button_dbdata:
